//! Codegen for `config/enums.yaml` → Rust `OUT_DIR/domain_enums_generated.rs`,
//! `app/src/lib/enums.generated.ts`, `schemas.enums.generated.ts`, SQL CHECK fragments.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::Path;

#[derive(serde::Deserialize)]
struct EnumsYaml {
    enums: BTreeMap<String, EnumDef>,
}

#[derive(serde::Deserialize)]
struct EnumDef {
    #[serde(default = "default_true")]
    generate_rust: bool,
    #[serde(default = "default_true")]
    generate_ts: bool,
    #[serde(default = "default_true")]
    generate_zod: bool,
    #[serde(default)]
    ts_const: Option<String>,
    #[serde(default)]
    zod_schema: Option<String>,
    #[serde(default)]
    sql_column: Option<String>,
    #[serde(default = "default_uppercase")]
    serde_rename_all: String,
    variants: Vec<VariantDef>,
}

#[derive(serde::Deserialize)]
struct VariantDef {
    #[serde(default)]
    rust: Option<String>,
    wire: String,
}

fn default_true() -> bool {
    true
}

fn default_uppercase() -> String {
    "UPPERCASE".into()
}

pub fn run(manifest_dir: &Path) {
    let yaml_path = manifest_dir.join("../../config/enums.yaml");
    let yaml_src = fs::read_to_string(&yaml_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", yaml_path.display()));
    let doc: EnumsYaml = serde_yaml::from_str(&yaml_src)
        .unwrap_or_else(|e| panic!("parse {}: {e}", yaml_path.display()));

    let out_dir_env = env::var("OUT_DIR").expect("OUT_DIR");
    let out_dir = Path::new(&out_dir_env);
    fs::write(
        out_dir.join("domain_enums_generated.rs"),
        render_rust(&doc.enums),
    )
    .expect("write domain_enums_generated.rs");

    let app_src = manifest_dir.join("../src/lib");
    fs::write(app_src.join("enums.generated.ts"), render_ts(&doc.enums))
        .expect("write enums.generated.ts");
    fs::write(
        app_src.join("schemas.enums.generated.ts"),
        render_zod(&doc.enums),
    )
    .expect("write schemas.enums.generated.ts");

    let sql_fragments = manifest_dir.join("migrations/generated/enum_check_fragments.sql");
    if let Some(parent) = sql_fragments.parent() {
        fs::create_dir_all(parent).expect("create migrations/generated");
    }
    fs::write(&sql_fragments, render_sql_fragments(&doc.enums))
        .expect("write enum_check_fragments.sql");

    println!("cargo:rerun-if-changed={}", yaml_path.display());
}

fn render_rust(enums: &BTreeMap<String, EnumDef>) -> String {
    let mut out = String::from(
        "// @generated by build/enums_codegen.rs from config/enums.yaml — do not edit.\n\
         use serde::{Deserialize, Serialize};\n\n",
    );
    for (name, def) in enums {
        if !def.generate_rust {
            continue;
        }
        let rename = &def.serde_rename_all;
        out.push_str("#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, sqlx::Type)]\n");
        out.push_str(&format!("#[sqlx(rename_all = \"{rename}\")]\n"));
        out.push_str(&format!("#[serde(rename_all = \"{rename}\")]\n"));
        out.push_str(&format!("pub enum {name} {{\n"));
        for v in &def.variants {
            let rust = v
                .rust
                .as_ref()
                .unwrap_or_else(|| panic!("enum {name}: variant missing rust name"));
            // Always pin wire strings: serde `rename_all = "UPPERCASE"` ≠ SQLite (`NICHT_ERSCHIENEN`).
            out.push_str(&format!(
                "    #[serde(rename = \"{}\")]\n    #[sqlx(rename = \"{}\")]\n",
                v.wire, v.wire
            ));
            out.push_str(&format!("    {rust},\n"));
        }
        out.push_str("}\n\n");
    }
    out
}

fn render_ts(enums: &BTreeMap<String, EnumDef>) -> String {
    let mut out = String::from(
        "/** @generated from config/enums.yaml — do not edit. Run `cargo build` to refresh. */\n\n",
    );
    for (name, def) in enums {
        if !def.generate_ts {
            continue;
        }
        let ts_const = def
            .ts_const
            .as_ref()
            .unwrap_or_else(|| panic!("enum {name}: missing ts_const"));
        let wires: Vec<&str> = def.variants.iter().map(|v| v.wire.as_str()).collect();
        let joined = wires
            .iter()
            .map(|w| format!("\"{w}\""))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("export const {ts_const} = [{joined}] as const;\n"));
        out.push_str(&format!(
            "export type {name} = (typeof {ts_const})[number];\n\n"
        ));
    }
    out
}

fn render_zod(enums: &BTreeMap<String, EnumDef>) -> String {
    let mut imports = Vec::new();
    let mut exports = String::new();
    for (name, def) in enums {
        if !def.generate_zod {
            continue;
        }
        let ts_const = def
            .ts_const
            .as_ref()
            .unwrap_or_else(|| panic!("enum {name}: missing ts_const"));
        let zod = def
            .zod_schema
            .as_ref()
            .unwrap_or_else(|| panic!("enum {name}: missing zod_schema"));
        imports.push(ts_const.clone());
        exports.push_str(&format!("export const {zod} = z.enum({ts_const});\n"));
    }
    let mut out = String::from(
        "/** @generated from config/enums.yaml — do not edit. */\nimport { z } from \"zod\";\n",
    );
    if !imports.is_empty() {
        out.push_str(&format!(
            "import {{ {} }} from \"./enums.generated\";\n\n",
            imports.join(", ")
        ));
    }
    out.push_str(&exports);
    out
}

fn render_sql_fragments(enums: &BTreeMap<String, EnumDef>) -> String {
    let mut out = String::from(
        "-- @generated from config/enums.yaml — reference CHECK fragments for migrations.\n\
         -- Do not edit; regenerate with `cargo build`.\n\n",
    );
    for (name, def) in enums {
        let Some(col) = &def.sql_column else {
            continue;
        };
        let wires: Vec<&str> = def.variants.iter().map(|v| v.wire.as_str()).collect();
        let in_list = wires
            .iter()
            .map(|w| format!("'{w}'"))
            .collect::<Vec<_>>()
            .join(",");
        out.push_str(&format!("-- {name} ({col})\n"));
        out.push_str(&format!("-- CHECK (... IN ({in_list}))\n\n"));
    }
    out
}
