//! Codegen for `config/rbac.yaml` → Rust `OUT_DIR/rbac_generated.rs` + `app/src/lib/rbac.generated.ts`.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::Path;

#[derive(serde::Deserialize)]
struct RbacYaml {
    role_sets: BTreeMap<String, Vec<String>>,
    permissions: BTreeMap<String, serde_yaml::Value>,
}

/// Run the RBAC codegen.
///
/// - `yaml_path` — absolute path to `config/rbac.yaml`.
/// - `ts_out_dir` — directory to receive `rbac.generated.ts`
///   (e.g. `app/src/lib/`).
///
/// The Rust output (`rbac_generated.rs`) is written to the **calling crate's**
/// `OUT_DIR` so that `include!(concat!(env!("OUT_DIR"), …))` resolves to the
/// same crate that defines `application::rbac`.
pub fn run(yaml_path: &Path, ts_out_dir: &Path) {
    let yaml_src = fs::read_to_string(yaml_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", yaml_path.display()));
    let doc: RbacYaml = serde_yaml::from_str(&yaml_src)
        .unwrap_or_else(|e| panic!("parse {}: {e}", yaml_path.display()));

    let mut resolved: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (action, value) in &doc.permissions {
        let roles = resolve_roles(value, &doc.role_sets, action);
        resolved.insert(action.clone(), roles);
    }

    let out_dir_env = env::var("OUT_DIR").expect("OUT_DIR");
    let out_dir = Path::new(&out_dir_env);
    fs::write(out_dir.join("rbac_generated.rs"), render_rust(&resolved))
        .expect("write rbac_generated.rs");

    let ts_path = ts_out_dir.join("rbac.generated.ts");
    fs::write(&ts_path, render_ts(&resolved)).expect("write rbac.generated.ts");

    println!("cargo:rerun-if-changed={}", yaml_path.display());
}

fn resolve_roles(
    value: &serde_yaml::Value,
    role_sets: &BTreeMap<String, Vec<String>>,
    action: &str,
) -> Vec<String> {
    match value {
        serde_yaml::Value::String(name) if name == "*" => {
            vec![
                "ARZT".into(),
                "REZEPTION".into(),
                "STEUERBERATER".into(),
                "PHARMABERATER".into(),
            ]
        }
        serde_yaml::Value::String(name) => role_sets
            .get(name)
            .unwrap_or_else(|| panic!("action {action}: unknown role_set {name}"))
            .clone(),
        serde_yaml::Value::Sequence(seq) => seq
            .iter()
            .map(|v| {
                v.as_str()
                    .unwrap_or_else(|| panic!("action {action}: role must be string"))
                    .to_string()
            })
            .collect(),
        other => panic!("action {action}: invalid permission value: {other:?}"),
    }
}

fn group_by_roles(resolved: &BTreeMap<String, Vec<String>>) -> BTreeMap<Vec<String>, Vec<String>> {
    let mut groups: BTreeMap<Vec<String>, Vec<String>> = BTreeMap::new();
    for (action, roles) in resolved {
        groups
            .entry(roles.clone())
            .or_default()
            .push(action.clone());
    }
    groups
}

fn render_rust(resolved: &BTreeMap<String, Vec<String>>) -> String {
    let mut actions: Vec<&String> = resolved.keys().collect();
    actions.sort();

    let mut out = String::from("// @generated by build.rs from config/rbac.yaml — DO NOT EDIT\n\n");
    out.push_str("pub fn rbac_matrix_allowed(action: &str, role: Role) -> bool {\n");
    out.push_str("    match action {\n");

    for (roles, grouped_actions) in group_by_roles(resolved) {
        let patterns: Vec<String> = grouped_actions.iter().map(|a| format!("\"{a}\"")).collect();
        out.push_str(&format!("        {} => ", patterns.join(" | ")));
        out.push_str(&render_rust_role_guard(&roles));
        out.push_str(",\n");
    }
    out.push_str("        _ => false,\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("/// All actions declared in `config/rbac.yaml` (stable order).\n");
    out.push_str("pub fn all_rbac_actions() -> &'static [&'static str] {\n");
    out.push_str("    &[\n");
    for action in &actions {
        out.push_str(&format!("        \"{action}\",\n"));
    }
    out.push_str("    ]\n");
    out.push_str("}\n");
    out
}

fn render_rust_role_guard(roles: &[String]) -> String {
    if roles.len() == 4 {
        return "true".to_string();
    }
    let parts: Vec<String> = roles
        .iter()
        .map(|r| format!("Role::{}", role_label(r)))
        .collect();
    if parts.len() == 1 {
        return format!("role == Role::{}", role_label(&roles[0]));
    }
    format!("matches!(role, {})", parts.join(" | "))
}

fn role_label(r: &str) -> &'static str {
    match r {
        "ARZT" => "Arzt",
        "REZEPTION" => "Rezeption",
        "STEUERBERATER" => "Steuerberater",
        "PHARMABERATER" => "Pharmaberater",
        _ => panic!("unknown role {r}"),
    }
}

fn render_ts(resolved: &BTreeMap<String, Vec<String>>) -> String {
    let mut actions: Vec<&String> = resolved.keys().collect();
    actions.sort();

    let mut out = String::from(
        "/** @generated by build.rs from config/rbac.yaml — DO NOT EDIT */\n\nexport function baseAllowedGenerated(action: string, role: string): boolean {\n    switch (action) {\n",
    );

    for (roles, grouped_actions) in group_by_roles(resolved) {
        for action in &grouped_actions {
            out.push_str(&format!("        case \"{action}\":\n"));
        }
        out.push_str(&format!(
            "            return {};\n",
            render_ts_role_guard(&roles)
        ));
    }
    out.push_str("        default:\n            return false;\n    }\n}\n\n");
    out.push_str("/** All actions declared in `config/rbac.yaml` (stable order). */\n");
    out.push_str("export const RBAC_ALL_ACTIONS = [\n");
    for action in &actions {
        out.push_str(&format!("    \"{action}\",\n"));
    }
    out.push_str("] as const;\n");
    out
}

fn render_ts_role_guard(roles: &[String]) -> String {
    if roles.len() == 4 {
        return "true".to_string();
    }
    let parts: Vec<String> = roles.iter().map(|r| format!("role === \"{r}\"")).collect();
    if parts.len() == 1 {
        return parts[0].clone();
    }
    parts.join(" || ")
}
