import type { Locale } from "./i18n";
import { useLocale } from "./i18n";

/** Demo/seed catalog names (English in SQLite) → localized labels for UI. */
const DE: Record<string, string> = {
    "Vitality test": "Vitalitätstest",
    "Occlusal analysis": "Okklusionsanalyse",
    "TMJ screening": "Kiefergelenk-Screening",
    "Professional cleaning": "Professionelle Zahnreinigung",
    "Airflow polish": "Airflow-Politur",
    "Fluoride varnish": "Fluoridlack",
    "Fissure sealant per tooth": "Fissurenversiegelung je Zahn",
    "Oral hygiene instruction": "Mundhygiene-Instruktion",
    "Desensitizing treatment": "Desensibilisierung",
    "One-surface composite": "Kompositfüllung 1 Fläche",
    "Two-surface composite": "Kompositfüllung 2 Flächen",
    "Three-surface composite": "Kompositfüllung 3 Flächen",
    "Composite buildup": "Kompositaufbau",
    "Glass ionomer filling": "Glasionomerfüllung",
    "Temporary filling": "Provisorische Füllung",
    "Pocket depth measurement": "Sondierungstiefenmessung",
    "Scaling & root planing quadrant": "Scaling und Wurzelglättung (Quadrant)",
    "Periodontal maintenance": "Parodontale Erhaltung",
    "Local antibiotic pocket": "Lokales Antibiotikum (Tasche)",
    Gingivectomy: "Gingivektomie",
    "Root canal anterior": "Wurzelkanalbehandlung Frontzahn",
    "Root canal premolar": "Wurzelkanalbehandlung Prämolar",
    "Root canal molar": "Wurzelkanalbehandlung Molar",
    "Endo retreatment": "Revision der Wurzelkanalbehandlung",
    "Pulp capping": "Überkappung",
    "Simple extraction": "Einfache Extraktion",
    "Surgical extraction": "Chirurgische Extraktion",
    "Wisdom tooth removal": "Weisheitszahnentfernung",
    Apicoectomy: "Wurzelspitzenresektion",
    "Implant uncovering": "Implantatfreilegung",
    "Abscess incision": "Abszessinzision",
    "Crown preparation": "Kronenpräparation",
    "Zirconia crown": "Zirkonkrone",
    "Bridge unit": "Brückenglied",
    "Partial denture": "Teilprothese",
    "Denture reline": "Prothesenunterfütterung",
    "Temporary crown": "Provisorische Krone",
    "Bleaching tray set": "Bleichschienen-Set",
    "In-office bleaching": "Praxisbleaching",
    "Composite veneer": "Kompositveneer",
    "Smile design consult": "Smile-Design-Beratung",
    "Splint therapy hard": "Harte Schienentherapie",
    "Splint adjustment": "Schienenanpassung",
    "Bruxism consult": "Bruxismus-Beratung",
    "Aligner consult": "Aligner-Beratung",
    Retainers: "Retainer",
    "Space maintainer": "Lückenhalter",
    "Impression / scan": "Abformung / Scan",
    "Shade matching": "Farbnahme",
    "Recall / checkup": "Kontrolluntersuchung / Recall",
    "New patient intake exam": "Erstuntersuchung (Neupatient)",
    "Child recall": "Kinder-Recall",
    "Emergency triage": "Notfall-Triage",
    "Periodontal charting": "Parodontalstatus",
    "Bitewing radiographs": "Bissflügelaufnahmen",
    "Panoramic X-ray": "Panoramaaufnahme",
    "Tooth extraction": "Zahnextraktion",
    "Partial denture consult": "Teilprothesen-Beratung",
};

const FR: Record<string, string> = {
    "Vitality test": "Test de vitalité",
    "Occlusal analysis": "Analyse occlusale",
    "TMJ screening": "Dépistage ATM",
    "Professional cleaning": "Détartrage professionnel",
    "Airflow polish": "Polissage airflow",
    "Fluoride varnish": "Vernis fluoré",
    "Fissure sealant per tooth": "Scellement de sillon par dent",
    "Oral hygiene instruction": "Conseils d'hygiène bucco-dentaire",
    "Desensitizing treatment": "Traitement désensibilisant",
    "One-surface composite": "Composite une face",
    "Two-surface composite": "Composite deux faces",
    "Three-surface composite": "Composite trois faces",
    "Composite buildup": "Reconstitution composite",
    "Glass ionomer filling": "Obturation verre ionomère",
    "Temporary filling": "Obturation temporaire",
    "Pocket depth measurement": "Mesure de profondeur de poche",
    "Scaling & root planing quadrant": "Surfaçage radiculaire (quadrant)",
    "Periodontal maintenance": "Maintenance parodontale",
    "Local antibiotic pocket": "Antibiotique local (poche)",
    Gingivectomy: "Gingivectomie",
    "Root canal anterior": "Traitement canalaire (dent antérieure)",
    "Root canal premolar": "Traitement canalaire (prémolaire)",
    "Root canal molar": "Traitement canalaire (molaire)",
    "Endo retreatment": "Reprise de traitement canalaire",
    "Pulp capping": "Coiffage pulpaire",
    "Simple extraction": "Extraction simple",
    "Surgical extraction": "Extraction chirurgicale",
    "Wisdom tooth removal": "Extraction de dent de sagesse",
    Apicoectomy: "Résection apicale",
    "Implant uncovering": "Dégagement d'implant",
    "Abscess incision": "Incision d'abcès",
    "Crown preparation": "Préparation de couronne",
    "Zirconia crown": "Couronne zircone",
    "Bridge unit": "Élément de bridge",
    "Partial denture": "Prothèse partielle",
    "Denture reline": "Rebasage de prothèse",
    "Temporary crown": "Couronne provisoire",
    "Bleaching tray set": "Gouttières de blanchiment",
    "In-office bleaching": "Blanchiment au cabinet",
    "Composite veneer": "Facettes composite",
    "Smile design consult": "Consultation smile design",
    "Splint therapy hard": "Gouttière occlusale dure",
    "Splint adjustment": "Ajustement de gouttière",
    "Bruxism consult": "Consultation bruxisme",
    "Aligner consult": "Consultation aligneurs",
    Retainers: "Contention",
    "Space maintainer": "Mainteneur d'espace",
    "Impression / scan": "Empreinte / scan",
    "Shade matching": "Prise de teinte",
    "Recall / checkup": "Contrôle / rappel",
    "New patient intake exam": "Bilan nouveau patient",
    "Child recall": "Rappel enfant",
    "Emergency triage": "Triage urgence",
    "Periodontal charting": "Charting parodontal",
    "Bitewing radiographs": "Rétroalvéolaires bitewing",
    "Panoramic X-ray": "Panoramique",
    "Tooth extraction": "Extraction dentaire",
    "Partial denture consult": "Consultation prothèse partielle",
};

const AR: Record<string, string> = {
    "Vitality test": "اختبار حيوية السن",
    "Occlusal analysis": "تحليل الإطباق",
    "TMJ screening": "فحص المفصل الفكي",
    "Professional cleaning": "تنظيف مهني",
    "Airflow polish": "تلميع بالهواء",
    "Fluoride varnish": "طلاء فلورايد",
    "Fissure sealant per tooth": "حشوة وقائية للشقوق (للسن)",
    "Oral hygiene instruction": "تعليمات صحة الفم",
    "Desensitizing treatment": "علاج حساسية الأسنان",
    "One-surface composite": "حشوة كمبوزيت سطح واحد",
    "Two-surface composite": "حشوة كمبوزيت سطحين",
    "Three-surface composite": "حشوة كمبوزيت ثلاثة أسطح",
    "Composite buildup": "بناء كمبوزيت",
    "Glass ionomer filling": "حشوة غلاس أيونومر",
    "Temporary filling": "حشوة مؤقتة",
    "Pocket depth measurement": "قياس عمق الجيوب",
    "Scaling & root planing quadrant": "تقليح وتسوية الجذور (ربع فك)",
    "Periodontal maintenance": "صيانة لثوية",
    "Local antibiotic pocket": "مضاد حيوي موضعي للجيب",
    Gingivectomy: "استئصال لثة",
    "Root canal anterior": "علاج عصب للسن الأمامي",
    "Root canal premolar": "علاج عصب للضاحك",
    "Root canal molar": "علاج عصب للرحى",
    "Endo retreatment": "إعادة علاج العصب",
    "Pulp capping": "تغطية اللب",
    "Simple extraction": "قلع بسيط",
    "Surgical extraction": "قلع جراحي",
    "Wisdom tooth removal": "قلع ضرس العقل",
    Apicoectomy: "قطع ذروة الجذر",
    "Implant uncovering": "كشف الزرعة",
    "Abscess incision": "شق خراج",
    "Crown preparation": "تحضير تاج",
    "Zirconia crown": "تاج زركونيا",
    "Bridge unit": "وحدة جسر",
    "Partial denture": "طقم جزئي",
    "Denture reline": "تبطين طقم",
    "Temporary crown": "تاج مؤقت",
    "Bleaching tray set": "طقم قوالب تبييض",
    "In-office bleaching": "تبييض في العيادة",
    "Composite veneer": "قشرة كمبوزيت",
    "Smile design consult": "استشارة تصميم الابتسامة",
    "Splint therapy hard": "علاج بجهاز إطباقي صلب",
    "Splint adjustment": "ضبط الجهاز الإطباقي",
    "Bruxism consult": "استشارة صرير الأسنان",
    "Aligner consult": "استشارة تقويم شفاف",
    Retainers: "مثبتات",
    "Space maintainer": "حافظ مسافة",
    "Impression / scan": "طبعة / مسح",
    "Shade matching": "مطابقة اللون",
    "Recall / checkup": "فحص دوري / مراجعة",
    "New patient intake exam": "فحص مريض جديد",
    "Child recall": "مراجعة الأطفال",
    "Emergency triage": "فرز طوارئ",
    "Periodontal charting": "مخطط لثوي",
    "Bitewing radiographs": "صور جناحية",
    "Panoramic X-ray": "صورة بانورامية",
    "Tooth extraction": "قلع سن",
    "Partial denture consult": "استشارة طقم جزئي",
};

const TABLES: Record<Locale, Record<string, string> | null> = {
    en: null,
    de: DE,
    fr: FR,
    ar: AR,
};

const SORTED_KEYS: Record<Locale, string[] | null> = {
    en: null,
    de: Object.keys(DE).sort((a, b) => b.length - a.length),
    fr: Object.keys(FR).sort((a, b) => b.length - a.length),
    ar: Object.keys(AR).sort((a, b) => b.length - a.length),
};

function escapeRegExp(value: string): string {
    return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Replace every English catalog phrase in mixed task/payment copy. */
export function clinicalServiceLabel(name: string, locale?: Locale): string {
    const trimmed = name.trim();
    if (!trimmed) return trimmed;
    const loc = locale ?? useLocale.getState().locale;
    const table = TABLES[loc];
    const keys = SORTED_KEYS[loc];
    if (!table || !keys) return trimmed;
    let out = trimmed;
    for (const key of keys) {
        const label = table[key];
        if (!label) continue;
        out = out.replace(new RegExp(escapeRegExp(key), "gi"), label);
    }
    return out;
}
