/** @generated by build.rs from config/rbac.yaml — DO NOT EDIT */

export function baseAllowedGenerated(action: string, role: string): boolean {
    switch (action) {
        case "audit.read":
        case "ops.audit_chain_ack":
        case "ops.backup":
        case "ops.dsgvo":
        case "ops.logs":
        case "ops.migration":
        case "ops.system":
        case "patient.read_medical":
        case "patient.write_medical":
        case "personal.read":
        case "personal.write":
        case "verwaltung.team.read":
        case "verwaltung.vorlagen.read":
        case "verwaltung.vorlagen.write":
        case "vorlagen.read":
        case "vorlagen.write":
            return role === "ARZT";
        case "patient.read":
        case "patient.read_documents":
        case "patient.write":
        case "termin.list_aerzte":
        case "termin.read":
        case "termin.write":
        case "verwaltung.praxisplanung.read":
        case "verwaltung.praxisplanung.write":
            return role === "ARZT" || role === "REZEPTION";
        case "bestellung.write":
        case "produkt.write":
        case "verwaltung.lager.write":
        case "verwaltung.vertraege.write":
            return role === "ARZT" || role === "REZEPTION" || role === "PHARMABERATER";
        case "finanzen.read":
        case "finanzen.tagesabschluss.write":
        case "finanzen.write":
        case "patient.behandlungen_list_for_zahlung":
        case "verwaltung.kataloge.read":
        case "verwaltung.kataloge.write":
            return role === "ARZT" || role === "REZEPTION" || role === "STEUERBERATER";
        case "bestellung.read":
        case "dashboard.read":
        case "produkt.read":
        case "verwaltung.lager.read":
        case "verwaltung.read":
        case "verwaltung.vertraege.read":
            return true;
        default:
            return false;
    }
}
