//! Clinical document PDFs — certificate, prescription, receipt.
//!
//! These renderers use the shared [`super::core`] / [`super::letterhead`]
//! layout system so all MeDoc PDFs (invoice, record, certificate, prescription,
//! receipt) have **identical margins, fonts, encoding, and page numbers**.
//!
//! Each document type has its own render function that interprets the shared
//! [`ClinicalPdfLayout`] input schema.
//!
//! Input = structured JSON (generated by the frontend).
//! Output = PDF bytes with DIN-5008 letterhead, signature block, and
//! privacy notice at the foot.

use crate::error::AppError;
use serde::Deserialize;

use super::core::{
    emit_multipage_pdf, truncate_cell, wrap_text, wrap_soft, PageBuilder, CONTENT_WIDTH, M_BOTTOM,
    M_LEFT, M_RIGHT,
};
use super::letterhead::{
    emit_continuation_header, emit_letterhead, emit_signature_block, Letterhead, MetaRow,
};

// ===========================================================================
// Input schemas
// ===========================================================================

/// A "label: value" row (e.g. "Vers.-Nr.: A123…").
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LabelValue {
    pub label: String,
    pub value: String,
}

/// Column layout for tables.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TableColumnLayout {
    /// Receipt: date (wide), description (wide), amount (narrow right).
    Receipt,
    /// Prescription (single): med · strength · dose · duration · PZN
    Prescription,
    /// Prescription (combo): pos · med · dose · duration · notes
    PrescriptionCombo,
    /// Even distribution (default).
    #[default]
    Even,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PdfTableSpec {
    pub title: Option<String>,
    pub headers: Vec<String>,
    pub rows: Vec<Vec<String>>,
    #[serde(default)]
    pub column_layout: TableColumnLayout,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DetailRecord {
    pub kind: String,
    pub period: String,
    pub details: Vec<String>,
}

/// Two-column box (e.g. patient data left + insurance right).
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TwoColumnBlock {
    pub left_title: Option<String>,
    pub left_lines: Vec<String>,
    pub right_title: Option<String>,
    pub right_lines: Vec<String>,
}

/// Full input for a clinical document rendering call.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClinicalPdfLayout {
    /// "certificate" | "prescription" | "receipt" | otherwise default
    pub kind: String,

    /// Practice letterhead (line 1 bold = name).
    pub practice_lines: Vec<String>,

    /// Right column at top — only when `meta_lines` is empty.
    #[serde(default)]
    pub header_right_lines: Vec<String>,

    /// Structured meta block (invoice no., date, …).
    #[serde(default)]
    pub meta_lines: Vec<LabelValue>,

    /// Address field (recipient).
    #[serde(default)]
    pub address_lines: Vec<String>,

    pub document_title: String,
    #[serde(default)]
    pub document_subtitle: Option<String>,

    /// Introductory paragraphs.
    #[serde(default)]
    pub intro_paragraphs: Vec<String>,

    /// Structured fields ("Label: Value" — compact single-line when possible).
    #[serde(default)]
    pub label_value_rows: Vec<LabelValue>,

    /// Patient panel (patient left, insurance right, etc.).
    #[serde(default)]
    pub two_column: Option<TwoColumnBlock>,

    #[serde(default)]
    pub tables: Vec<PdfTableSpec>,

    /// Detail blocks (e.g. sick-leave period per diagnosis).
    #[serde(default)]
    pub detail_records: Vec<DetailRecord>,

    /// Totals rows (for receipt / invoice).
    #[serde(default)]
    pub totals: Vec<LabelValue>,

    /// Closing paragraphs (e.g. notices, instructions).
    #[serde(default)]
    pub closing_paragraphs: Vec<String>,

    /// Signature block — line 1 = name, then professional title, ZANR, BSNR.
    #[serde(default)]
    pub signature_lines: Vec<String>,

    /// Footer right (issue date, place).
    #[serde(default)]
    pub footer_meta_lines: Vec<LabelValue>,

    /// Provider professional title for the default signature block.
    #[serde(default)]
    pub clinician_professional_title: Option<String>,
    #[serde(default)]
    pub clinician_zanr: Option<String>,
    #[serde(default)]
    pub clinician_bsnr: Option<String>,
}

// ===========================================================================
// Column layouts per document type
// ===========================================================================

/// Return X start positions per column for a given layout.
fn table_column_xs(layout: TableColumnLayout, ncol: usize) -> Vec<i32> {
    let ncol = ncol.max(1);
    match layout {
        // Date narrow · position medium · short description wide (rest to right)
        TableColumnLayout::Receipt if ncol >= 3 => {
            vec![M_LEFT, M_LEFT + 72, M_LEFT + 198]
        }
        TableColumnLayout::Prescription if ncol >= 5 => vec![
            M_LEFT,
            M_LEFT + 130,
            M_LEFT + 220,
            M_LEFT + 295,
            M_LEFT + 365,
        ],
        TableColumnLayout::PrescriptionCombo if ncol >= 5 => vec![
            M_LEFT,
            M_LEFT + 38,
            M_LEFT + 170,
            M_LEFT + 290,
            M_LEFT + 365,
        ],
        _ => {
            let step = CONTENT_WIDTH / ncol as i32;
            (0..ncol).map(|i| M_LEFT + i as i32 * step).collect()
        }
    }
}

/// Compute max characters per column from the X positions.
fn column_char_widths(xs: &[i32]) -> Vec<usize> {
    let mut w = Vec::with_capacity(xs.len());
    for i in 0..xs.len() {
        let next = xs.get(i + 1).copied().unwrap_or(M_RIGHT);
        let width_pt = (next - xs[i]).max(20);
        // At 9 pt Helvetica: ~5 pt per character
        w.push(((width_pt / 5).max(6)) as usize);
    }
    w
}

// ===========================================================================
// Render function
// ===========================================================================

/// `LabelValue` → `MetaRow` conversion for the letterhead.
fn to_meta_rows(items: &[LabelValue]) -> Vec<MetaRow> {
    items
        .iter()
        .map(|x| MetaRow::new(&x.label, &x.value))
        .collect()
}

/// Main entry: render a clinical PDF.
pub fn render_clinical_layout(doc: &ClinicalPdfLayout) -> Result<Vec<u8>, AppError> {
    let mut pb = PageBuilder::new();

    match doc.kind.as_str() {
        "certificate" => render_certificate(&mut pb, doc),
        "prescription" => render_prescription(&mut pb, doc),
        "receipt" => render_receipt(&mut pb, doc),
        _ => render_generic(&mut pb, doc),
    }

    emit_clinical_privacy_footer(&mut pb, &doc.kind);

    let pages = pb.finish();
    emit_multipage_pdf(&pages, &format!("{} {}", doc.kind, doc.document_title))
}

/// Plain preview when the frontend sends `bodyLines` only (no `layoutJson`).
/// Uses the same letterhead + footer stack as structured clinical exports.
pub fn render_plain_preview(
    kind: &str,
    template_name: &str,
    footer: &str,
    body_pt: i32,
    body_lines: &[String],
) -> Result<Vec<u8>, AppError> {
    let fs = body_pt.clamp(8, 18);
    let wrap_cols = 86usize.saturating_sub((18 - fs) as usize * 2);

    let cleaned: Vec<String> = body_lines
        .iter()
        .map(|l| crate::infrastructure::clinical_text_format::plain_text_for_pdf(l))
        .collect();

    let practice_lines: Vec<String> = cleaned
        .first()
        .filter(|s| !s.trim().is_empty())
        .map(|s| vec![s.clone()])
        .unwrap_or_default();
    let body_start = if practice_lines.is_empty() { 0 } else { 1 };

    let mut pb = PageBuilder::new();
    let lh = Letterhead {
        practice_lines: &practice_lines,
        meta_rows: &[],
        address_lines: &[],
        header_right_lines: &[],
        show_sender_hint: false,
    };
    emit_letterhead(&mut pb, &lh);

    pb.text(M_LEFT, 14, true, template_name);
    pb.advance(18);
    pb.text(M_LEFT, 9, false, &format!("Document type: {kind}"));
    pb.advance(14);
    pb.hline(M_LEFT, M_RIGHT);
    pb.advance(16);

    for raw in &cleaned[body_start..] {
        if raw.trim().is_empty() {
            pb.advance(fs / 2);
            continue;
        }
        pb.paragraph(raw, fs, wrap_cols, 0);
    }

    if !footer.trim().is_empty() {
        pb.advance(8);
        pb.hline(M_LEFT, M_RIGHT);
        pb.advance(10);
        for chunk in wrap_soft(footer.trim(), wrap_cols) {
            pb.text(M_LEFT, 8, false, &chunk);
            pb.advance(11);
        }
    }

    emit_clinical_privacy_footer(&mut pb, kind);

    let pages = pb.finish();
    emit_multipage_pdf(&pages, &format!("Vorschau {template_name}"))
}

fn emit_clinical_privacy_footer(pb: &mut PageBuilder, kind: &str) {
    if kind == "receipt" {
        return;
    }
    pb.ensure_space(40);
    pb.advance(12);
    pb.hline(M_LEFT, M_RIGHT);
    pb.advance(10);
    pb.text(
        M_LEFT,
        7,
        false,
        "Vertrauliche Patientendaten gem. § 630f BGB / Kind. 9 DSGVO. Weitergabe nur an Berechtigte.",
    );
}

// ---------------------------------------------------------------------------
// ATTEST  (Muster-1-Stil)
// ---------------------------------------------------------------------------

fn render_certificate(pb: &mut PageBuilder, doc: &ClinicalPdfLayout) {
    // Letterhead — certificates usually go to the patient directly, so
    // address_lines beachten
    let meta_rows = to_meta_rows(&doc.meta_lines);
    let lh = Letterhead {
        practice_lines: &doc.practice_lines,
        meta_rows: &meta_rows,
        address_lines: &doc.address_lines,
        header_right_lines: &doc.header_right_lines,
        show_sender_hint: !doc.address_lines.is_empty(),
    };
    emit_letterhead(pb, &lh);

    // Titel zentriert
    pb.text_center(17, true, &doc.document_title);
    pb.advance(22);
    if let Some(sub) = doc
        .document_subtitle
        .as_deref()
        .filter(|s| !s.trim().is_empty())
    {
        pb.text_center(10, false, sub);
        pb.advance(14);
    }

    pb.hline(M_LEFT + 100, M_RIGHT - 100);
    pb.advance(16);

    render_intro(pb, &doc.intro_paragraphs);
    emit_label_value_rows(pb, &doc.label_value_rows);

    for table in &doc.tables {
        emit_table(
            pb,
            table,
            (
                doc.practice_lines
                    .first()
                    .map(|s| s.as_str())
                    .unwrap_or("MeDoc"),
                &doc.document_title,
            ),
        );
    }

    emit_detail_records(pb, &doc.detail_records);

    for p in &doc.closing_paragraphs {
        if !p.trim().is_empty() {
            pb.paragraph(p, 10, 84, 0);
        }
    }

    emit_default_or_custom_signature(pb, doc);
}

// ---------------------------------------------------------------------------
// REZEPT  (Muster-16-Stil — Privatrezept)
// ---------------------------------------------------------------------------

fn render_prescription(pb: &mut PageBuilder, doc: &ClinicalPdfLayout) {
    let meta_rows = to_meta_rows(&doc.meta_lines);
    let lh = Letterhead {
        practice_lines: &doc.practice_lines,
        meta_rows: &meta_rows,
        address_lines: &[],
        header_right_lines: &[],
        show_sender_hint: false,
    };
    emit_letterhead(pb, &lh);

    // Large "Prescription" title on the left, optional subtitle (private / statutory / BtM)
    pb.text(M_LEFT, 18, true, &doc.document_title);
    pb.advance(22);
    if let Some(sub) = doc
        .document_subtitle
        .as_deref()
        .filter(|s| !s.trim().is_empty())
    {
        pb.text(M_LEFT, 10, false, sub);
        pb.advance(14);
    }
    pb.hline(M_LEFT, M_RIGHT);
    pb.advance(18);

    // Patient panel (two columns)
    if let Some(ref tc) = doc.two_column {
        emit_two_column_panel(pb, tc);
    }

    emit_label_value_rows(pb, &doc.label_value_rows);

    // Tables (title may already contain "Rp." — avoid double prefix)
    if !doc.tables.is_empty() {
        pb.advance(6);
        for table in &doc.tables {
            emit_table(
                pb,
                table,
                (
                    doc.practice_lines
                        .first()
                        .map(|s| s.as_str())
                        .unwrap_or("MeDoc"),
                    &doc.document_title,
                ),
            );
        }
    }

    render_intro(pb, &doc.intro_paragraphs);

    for p in &doc.closing_paragraphs {
        if !p.trim().is_empty() {
            pb.paragraph(p, 10, 84, 0);
        }
    }

    emit_default_or_custom_signature(pb, doc);
}

// ---------------------------------------------------------------------------
// QUITTUNG  (GoBD-konform)
// ---------------------------------------------------------------------------

fn render_receipt(pb: &mut PageBuilder, doc: &ClinicalPdfLayout) {
    let meta_rows = to_meta_rows(&doc.meta_lines);
    let lh = Letterhead {
        practice_lines: &doc.practice_lines,
        meta_rows: &meta_rows,
        address_lines: &doc.address_lines,
        header_right_lines: &[],
        show_sender_hint: !doc.address_lines.is_empty(),
    };
    emit_letterhead(pb, &lh);

    pb.text_center(15, true, &doc.document_title);
    pb.advance(20);
    if let Some(sub) = doc
        .document_subtitle
        .as_deref()
        .filter(|s| !s.trim().is_empty())
    {
        pb.text_center(11, false, sub);
        pb.advance(14);
    }
    pb.hline(M_LEFT, M_RIGHT);
    pb.advance(14);

    render_intro(pb, &doc.intro_paragraphs);
    emit_label_value_rows(pb, &doc.label_value_rows);

    // Totals + service table as one contiguous block (uniform gray)
    if let Some(table) = doc.tables.first() {
        let cont = (
            doc.practice_lines
                .first()
                .map(|s| s.as_str())
                .unwrap_or("MeDoc"),
            doc.document_title.as_str(),
        );
        emit_receipt_totals_and_table(pb, &doc.totals, table, cont);
        for extra in doc.tables.iter().skip(1) {
            emit_table(pb, extra, cont);
        }
    } else {
        emit_receipt_totals(pb, &doc.totals);
    }

    for p in &doc.closing_paragraphs {
        if !p.trim().is_empty() {
            pb.paragraph(p, 9, 90, 0);
        }
    }

    emit_default_or_custom_signature(pb, doc);
}

// ---------------------------------------------------------------------------
// GENERIC  (fallback for unknown kind)
// ---------------------------------------------------------------------------

fn render_generic(pb: &mut PageBuilder, doc: &ClinicalPdfLayout) {
    let meta_rows = to_meta_rows(&doc.meta_lines);
    let lh = Letterhead {
        practice_lines: &doc.practice_lines,
        meta_rows: &meta_rows,
        address_lines: &doc.address_lines,
        header_right_lines: &doc.header_right_lines,
        show_sender_hint: !doc.address_lines.is_empty(),
    };
    emit_letterhead(pb, &lh);

    pb.text(M_LEFT, 14, true, &doc.document_title);
    pb.advance(18);
    if let Some(sub) = doc
        .document_subtitle
        .as_deref()
        .filter(|s| !s.trim().is_empty())
    {
        pb.text(M_LEFT, 10, false, sub);
        pb.advance(14);
    }

    render_intro(pb, &doc.intro_paragraphs);
    emit_label_value_rows(pb, &doc.label_value_rows);

    if let Some(ref tc) = doc.two_column {
        emit_two_column_panel(pb, tc);
    }

    for table in &doc.tables {
        emit_table(
            pb,
            table,
            (
                doc.practice_lines
                    .first()
                    .map(|s| s.as_str())
                    .unwrap_or("MeDoc"),
                &doc.document_title,
            ),
        );
    }

    emit_detail_records(pb, &doc.detail_records);
    emit_totals_block(pb, &doc.totals);

    for p in &doc.closing_paragraphs {
        if !p.trim().is_empty() {
            pb.paragraph(p, 10, 84, 0);
        }
    }

    emit_default_or_custom_signature(pb, doc);
}

// ===========================================================================
// Bausteine
// ===========================================================================

fn render_intro(pb: &mut PageBuilder, paragraphs: &[String]) {
    for p in paragraphs {
        if p.trim().is_empty() {
            pb.advance(6);
            continue;
        }
        // Heuristic: if the element is a colon headline
        // ("Notee:", "Diagnosis:") AND short AND no further colons
        // inside, treat it as a section title.
        let trimmed = p.trim_end();
        let is_heading = trimmed.ends_with(':')
            && trimmed.len() <= 40
            && trimmed[..trimmed.len() - 1]
                .chars()
                .filter(|c| *c == ':')
                .count()
                == 0;

        if is_heading {
            pb.ensure_space(40);
            pb.advance(6);
            pb.text(M_LEFT, 11, true, &trimmed[..trimmed.len() - 1]);
            pb.advance(14);
        } else {
            pb.paragraph(p, 10, 84, 0);
            pb.advance(3);
        }
    }
}

fn emit_label_value_rows(pb: &mut PageBuilder, rows: &[LabelValue]) {
    for row in rows {
        pb.ensure_space(36);
        let multiline = row.value.contains('\n');
        let compact = !multiline && row.value.chars().count() <= 70;

        if compact {
            pb.text(M_LEFT, 9, true, &format!("{}:", row.label));
            pb.text(M_LEFT + 145, 10, false, row.value.trim());
            pb.advance(14);
        } else {
            pb.text(M_LEFT, 9, true, &row.label);
            pb.advance(12);
            // Multi-line values: wrap each line separately so structure
            // is preserved
            for raw in row.value.split('\n') {
                if raw.trim().is_empty() {
                    pb.advance(6);
                    continue;
                }
                for chunk in wrap_text(raw, 84) {
                    pb.ensure_space(30);
                    pb.text(M_LEFT + 4, 10, false, &chunk);
                    pb.advance(12);
                }
            }
            pb.advance(6);
        }
    }
}

fn emit_two_column_panel(pb: &mut PageBuilder, block: &TwoColumnBlock) {
    pb.ensure_space(110);
    let panel_h = 80;
    let panel_bottom = pb.y - panel_h + 4;
    let title_band_y = pb.y - 12;

    // Rahmen
    pb.stroke_rect(M_LEFT, panel_bottom, CONTENT_WIDTH, panel_h);
    // Heller Titel-Streifen oben
    pb.fill_rect(M_LEFT + 1, title_band_y, CONTENT_WIDTH - 2, 13, 0.94);

    let mid_x = M_LEFT + CONTENT_WIDTH / 2;
    let title_y = pb.y - 8;

    // Titel
    let prev_y = pb.y;
    pb.y = title_y;
    pb.text(
        M_LEFT + 8,
        9,
        true,
        block.left_title.as_deref().unwrap_or("Patient"),
    );
    if let Some(t) = block.right_title.as_deref() {
        pb.text(mid_x + 4, 9, true, t);
    }
    pb.y = prev_y;

    // Linke Spalte
    let mut yl = title_y - 14;
    for line in &block.left_lines {
        for chunk in wrap_soft(line, 36) {
            pb.y = yl;
            pb.text(M_LEFT + 10, 9, false, &chunk);
            yl -= 11;
        }
    }

    // Rechte Spalte
    let mut yr = title_y - 14;
    for line in &block.right_lines {
        for chunk in wrap_soft(line, 36) {
            pb.y = yr;
            pb.text(mid_x + 6, 9, false, &chunk);
            yr -= 11;
        }
    }

    pb.y = panel_bottom - 12;
}

fn emit_table(pb: &mut PageBuilder, table: &PdfTableSpec, continuation: (&str, &str)) {
    let ncol = table
        .headers
        .len()
        .max(table.rows.iter().map(|r| r.len()).max().unwrap_or(0))
        .max(1);
    let col_xs = table_column_xs(table.column_layout, ncol);
    let col_chars = column_char_widths(&col_xs);

    if let Some(t) = table.title.as_deref().filter(|s| !s.is_empty()) {
        pb.ensure_space(80);
        pb.advance(4);
        pb.text(M_LEFT, 11, true, t);
        pb.advance(14);
    }

    pb.ensure_space(70);

    // Table header
    pb.table_header_band(M_LEFT, pb.y + 2, CONTENT_WIDTH);
    for (ci, h) in table.headers.iter().enumerate() {
        let x = col_xs.get(ci).copied().unwrap_or(M_LEFT);
        pb.text(x + 2, 9, true, h);
    }
    pb.advance(13);
    pb.hline(M_LEFT, M_RIGHT);
    pb.advance(10);

    emit_table_data_rows(pb, table, &col_xs, &col_chars, continuation);
}

fn emit_detail_records(pb: &mut PageBuilder, records: &[DetailRecord]) {
    for rec in records {
        let detail_lines: usize = rec
            .details
            .iter()
            .map(|d| wrap_soft(d, 80).len().max(1))
            .sum();
        let total_h = 14 + 24 + 14 + (detail_lines as i32 * 11) + 12;
        pb.ensure_space(total_h);

        let box_bottom = pb.y - total_h + 8;
        pb.fill_rect(M_LEFT, box_bottom, CONTENT_WIDTH, total_h - 8, 0.97);

        pb.advance(2);
        pb.text(M_LEFT + 6, 9, true, "Type");
        pb.advance(12);
        for chunk in wrap_soft(&rec.kind, 80) {
            pb.text(M_LEFT + 6, 9, false, &chunk);
            pb.advance(11);
        }
        pb.advance(2);

        pb.text(M_LEFT + 6, 9, true, "Period");
        pb.advance(12);
        for chunk in wrap_soft(&rec.period, 80) {
            pb.text(M_LEFT + 6, 9, false, &chunk);
            pb.advance(11);
        }
        pb.advance(2);

        pb.text(M_LEFT + 6, 9, true, "Details");
        pb.advance(12);
        for detail in &rec.details {
            for chunk in wrap_soft(detail, 80) {
                pb.text(M_LEFT + 6, 9, false, &chunk);
                pb.advance(11);
            }
        }
        pb.advance(8);
    }
}

/// Uniform padding in receipt tables (totals + header + rows).
const RECEIPT_PAD: i32 = 10;
const RECEIPT_ROW_H: i32 = 14;
const RECEIPT_HEADER_H: i32 = 18;
const RECEIPT_BAND_GRAY: f64 = 0.93;

fn is_total_label(label: &str) -> bool {
    let l = label.to_ascii_lowercase();
    l.contains("gesamt") || l.contains("endbetrag") || l.contains("total")
}

fn emit_receipt_totals(pb: &mut PageBuilder, totals: &[LabelValue]) {
    if totals.is_empty() {
        return;
    }
    pb.ensure_space(60);
    pb.advance(4);
    let mut y = pb.y - 4;
    for (i, row) in totals.iter().enumerate() {
        let bold = is_total_label(&row.label);
        if bold {
            pb.fill_rect(
                M_LEFT,
                y - RECEIPT_ROW_H + 2,
                CONTENT_WIDTH,
                RECEIPT_ROW_H,
                RECEIPT_BAND_GRAY,
            );
        }
        pb.y = y;
        pb.text(M_LEFT + RECEIPT_PAD, 10, bold, &format!("{}:", row.label));
        pb.text_right(M_RIGHT - RECEIPT_PAD, 10, bold, &row.value);
        if i + 1 < totals.len() {
            y -= RECEIPT_ROW_H;
        }
    }
    pb.y = y - RECEIPT_ROW_H - 6;
}

/// Totals block + table header in **one** gray band (no white gap between).
fn emit_receipt_totals_and_table(
    pb: &mut PageBuilder,
    totals: &[LabelValue],
    table: &PdfTableSpec,
    continuation: (&str, &str),
) {
    let ncol = table
        .headers
        .len()
        .max(table.rows.iter().map(|r| r.len()).max().unwrap_or(0))
        .max(1);
    let col_xs = table_column_xs(table.column_layout, ncol);
    let col_chars = column_char_widths(&col_xs);

    pb.ensure_space(90);

    let totals_rows = totals.len() as i32;
    let totals_h = if totals.is_empty() {
        0
    } else {
        totals_rows * RECEIPT_ROW_H + 4
    };
    let combined_h = totals_h + RECEIPT_HEADER_H;

    if !totals.is_empty() {
        pb.advance(4);
    }
    let band_bottom = pb.y - combined_h;

    let mut y = pb.y - 4;
    if !totals.is_empty() {
        for (i, row) in totals.iter().enumerate() {
            let bold = is_total_label(&row.label);
            if bold {
                pb.fill_rect(
                    M_LEFT,
                    y - RECEIPT_ROW_H + 2,
                    CONTENT_WIDTH,
                    RECEIPT_ROW_H,
                    RECEIPT_BAND_GRAY,
                );
            }
            pb.y = y;
            pb.text(M_LEFT + RECEIPT_PAD, 10, bold, &format!("{}:", row.label));
            pb.text_right(M_RIGHT - RECEIPT_PAD, 10, bold, &row.value);
            if i + 1 < totals.len() {
                y -= RECEIPT_ROW_H;
            }
        }
    }

    let header_baseline = if totals.is_empty() {
        pb.y - 6
    } else {
        band_bottom + RECEIPT_HEADER_H - 6
    };
    for (ci, h) in table.headers.iter().enumerate() {
        let x = col_xs.get(ci).copied().unwrap_or(M_LEFT);
        pb.y = header_baseline;
        pb.text(x + RECEIPT_PAD, 9, true, h);
    }

    pb.y = band_bottom;
    pb.hline(M_LEFT, M_RIGHT);
    pb.advance(10);

    emit_table_data_rows(pb, table, &col_xs, &col_chars, continuation);
}

/// Table rows without re-emitting the header band (after [`emit_receipt_totals_and_table`]).
fn emit_table_data_rows(
    pb: &mut PageBuilder,
    table: &PdfTableSpec,
    col_xs: &[i32],
    col_chars: &[usize],
    continuation: (&str, &str),
) {
    let ncol = table
        .headers
        .len()
        .max(table.rows.iter().map(|r| r.len()).max().unwrap_or(0))
        .max(1);

    for (ri, row) in table.rows.iter().enumerate() {
        let mut wrapped: Vec<Vec<String>> = Vec::with_capacity(ncol);
        let mut row_lines = 1usize;
        for ci in 0..ncol {
            let cell = row.get(ci).map(|s| s.as_str()).unwrap_or("");
            let max_chars = col_chars.get(ci).copied().unwrap_or(20);
            let clipped = truncate_cell(cell, max_chars.saturating_mul(2));
            let w = wrap_soft(&clipped, max_chars);
            row_lines = row_lines.max(w.len().max(1));
            wrapped.push(w);
        }

        let row_height = row_lines as i32 * 12 + 6;
        if pb.y < M_BOTTOM + row_height + 20 {
            pb.break_page();
            emit_continuation_header(pb, continuation.0, continuation.1);
            pb.table_header_band(M_LEFT, pb.y + 2, CONTENT_WIDTH);
            for (ci, h) in table.headers.iter().enumerate() {
                let x = col_xs.get(ci).copied().unwrap_or(M_LEFT);
                pb.text(x + RECEIPT_PAD, 9, true, h);
            }
            pb.advance(13);
            pb.hline(M_LEFT, M_RIGHT);
            pb.advance(10);
        }

        if ri % 2 == 1 {
            pb.fill_rect(M_LEFT, pb.y - row_height, CONTENT_WIDTH, row_height, 0.97);
        }

        let base_y = pb.y;
        for li in 0..row_lines {
            for ci in 0..ncol {
                let x = col_xs.get(ci).copied().unwrap_or(M_LEFT);
                let chunk = wrapped
                    .get(ci)
                    .and_then(|w| w.get(li))
                    .map(|s| s.as_str())
                    .unwrap_or("");
                if !chunk.is_empty() {
                    let prev = pb.y;
                    pb.y = base_y - li as i32 * 12;
                    pb.text(x + RECEIPT_PAD, 9, false, chunk);
                    pb.y = prev;
                }
            }
        }
        pb.advance(row_height);
    }
    pb.advance(8);
}

fn emit_totals_block(pb: &mut PageBuilder, totals: &[LabelValue]) {
    if totals.is_empty() {
        return;
    }
    pb.ensure_space(40 + totals.len() as i32 * 14);
    pb.advance(8);
    pb.hline(300, M_RIGHT);
    pb.advance(3);
    pb.hline(300, M_RIGHT);
    pb.advance(14);
    for row in totals {
        let bold = is_total_label(&row.label);
        pb.text_right(380, 10, bold, &format!("{}:", row.label));
        pb.text_right(M_RIGHT, 10, bold, &row.value);
        pb.advance(14);
    }
    pb.advance(8);
}

/// When `signature_lines` is populated, use those lines directly;
/// otherwise use the default signature block from `behandler_*` fields.
fn emit_default_or_custom_signature(pb: &mut PageBuilder, doc: &ClinicalPdfLayout) {
    if doc.signature_lines.is_empty() {
        // No custom block — default signature block. Provider name
        // is not available separately on this path; only professional
        // title, ZANR, and BSNR are emitted.
        emit_signature_block(
            pb,
            None,
            doc.clinician_professional_title.as_deref(),
            doc.clinician_zanr.as_deref(),
            doc.clinician_bsnr.as_deref(),
            true,
        );
        emit_footer_meta(pb, &doc.footer_meta_lines);
        return;
    }

    // Custom signature lines
    pb.ensure_space(80);
    pb.advance(20);
    pb.hline(M_LEFT, M_RIGHT);
    pb.advance(20);
    pb.hline_at(M_LEFT, pb.y, M_LEFT + 180);
    pb.advance(14);
    for (i, line) in doc.signature_lines.iter().enumerate() {
        let bold = i == 0;
        let size = if i == 0 { 10 } else { 9 };
        pb.text(M_LEFT, size, bold, line);
        pb.advance(size + 2);
    }
    pb.advance(4);
    pb.text(M_LEFT, 8, false, "(Practice stamp)");

    emit_footer_meta(pb, &doc.footer_meta_lines);
}

fn emit_footer_meta(pb: &mut PageBuilder, meta: &[LabelValue]) {
    if meta.is_empty() {
        return;
    }
    // Ensure meta lines appear below the signature block
    pb.advance(10);
    for row in meta {
        pb.text(M_LEFT, 8, false, &row.label);
        pb.text_right(M_RIGHT, 9, false, &row.value);
        pb.advance(12);
    }
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn practice() -> Vec<String> {
        vec![
            "Zahnarztpraxis Dr. Test".into(),
            "Teststraße 1".into(),
            "10115 Berlin".into(),
            "Tel: 030/12345".into(),
        ]
    }

    fn meta() -> Vec<LabelValue> {
        vec![
            LabelValue {
                label: "Date".into(),
                value: "19.04.2026".into(),
            },
            LabelValue {
                label: "Document-Nr.".into(),
                value: "AT-001".into(),
            },
        ]
    }

    #[test]
    fn renders_certificate() {
        let doc = ClinicalPdfLayout {
            kind: "certificate".into(),
            practice_lines: practice(),
            header_right_lines: vec![],
            meta_lines: meta(),
            address_lines: vec!["Max Mustermann".into(), "Musterstr. 1".into()],
            document_title: "MEDICAL CERTIFICATE".into(),
            document_subtitle: Some("SICK_LEAVE".into()),
            intro_paragraphs: vec![
                "This certifies that the person named below …".into()
            ],
            label_value_rows: vec![
                LabelValue {
                    label: "Patient".into(),
                    value: "Max Mustermann".into(),
                },
                LabelValue {
                    label: "Date of birth".into(),
                    value: "01.01.1980".into(),
                },
                LabelValue {
                    label: "ICD-10".into(),
                    value: "K02.1 — Karies des Dentins".into(),
                },
            ],
            two_column: None,
            tables: vec![],
            detail_records: vec![],
            totals: vec![],
            closing_paragraphs: vec!["Place, date: Berlin, 19.04.2026".into()],
            signature_lines: vec![],
            footer_meta_lines: vec![],
            clinician_professional_title: Some("Zahnärztin".into()),
            clinician_zanr: Some("987654321".into()),
            clinician_bsnr: Some("123456789".into()),
        };
        let pdf = render_clinical_layout(&doc).unwrap();
        assert!(pdf.starts_with(b"%PDF-1.4"));
        assert!(pdf.ends_with(b"%%EOF\n"));
        let text = String::from_utf8_lossy(&pdf);
        assert!(text.contains("CERTIFICATE") || text.contains("MEDICAL"));
    }

    #[test]
    fn renders_prescription_with_two_column_panel() {
        let doc = ClinicalPdfLayout {
            kind: "prescription".into(),
            practice_lines: practice(),
            header_right_lines: vec![],
            meta_lines: meta(),
            address_lines: vec![],
            document_title: "Prescription".into(),
            document_subtitle: Some("Privatrezept".into()),
            intro_paragraphs: vec![],
            label_value_rows: vec![LabelValue {
                label: "Prescription date".into(),
                value: "19.04.2026".into(),
            }],
            two_column: Some(TwoColumnBlock {
                left_title: Some("Patient".into()),
                left_lines: vec![
                    "Max Mustermann".into(),
                    "geb. 01.01.1980".into(),
                    "Musterstr. 1, 10115 Berlin".into(),
                ],
                right_title: Some("Krankenkasse".into()),
                right_lines: vec!["AOK Nordost".into(), "IK 109 519 005".into()],
            }),
            tables: vec![PdfTableSpec {
                title: None,
                headers: vec![
                    "Medication".into(),
                    "Dosage".into(),
                    "Duration".into(),
                    "PZN".into(),
                    "Note".into(),
                ],
                rows: vec![vec![
                    "Ibuprofen 600".into(),
                    "1-1-1".into(),
                    "5 Tage".into(),
                    "12345678".into(),
                    "aut idem".into(),
                ]],
                column_layout: TableColumnLayout::Prescription,
            }],
            detail_records: vec![],
            totals: vec![],
            closing_paragraphs: vec![],
            signature_lines: vec![],
            footer_meta_lines: vec![],
            clinician_professional_title: Some("Zahnarzt".into()),
            clinician_zanr: Some("987654321".into()),
            clinician_bsnr: Some("123456789".into()),
        };
        let pdf = render_clinical_layout(&doc).unwrap();
        assert!(pdf.starts_with(b"%PDF-1.4"));
    }

    #[test]
    fn renders_receipt() {
        let doc = ClinicalPdfLayout {
            kind: "receipt".into(),
            practice_lines: practice(),
            header_right_lines: vec![],
            meta_lines: vec![
                LabelValue {
                    label: "Receipt-Nr.".into(),
                    value: "QU-2026-0001".into(),
                },
                LabelValue {
                    label: "Date".into(),
                    value: "19.04.2026".into(),
                },
            ],
            address_lines: vec!["Max Mustermann".into()],
            document_title: "QUITTUNG".into(),
            document_subtitle: Some("Payment receipt".into()),
            intro_paragraphs: vec![
                "Hiermit bestätigen wir den Erhalt des unten ausgewiesenen Betrages.".into(),
            ],
            label_value_rows: vec![
                LabelValue {
                    label: "Payment method".into(),
                    value: "Barzahlung".into(),
                },
                LabelValue {
                    label: "ServiceItem".into(),
                    value: "Checkup".into(),
                },
            ],
            two_column: None,
            tables: vec![],
            detail_records: vec![],
            totals: vec![LabelValue {
                label: "Total amount".into(),
                value: "45,00 €".into(),
            }],
            closing_paragraphs: vec![
                "Umsatzsteuerbefreit gem. § 4 Nr. 14 UStG.".into(),
                "Betrag dankend erhalten.".into(),
            ],
            signature_lines: vec![],
            footer_meta_lines: vec![],
            clinician_professional_title: None,
            clinician_zanr: None,
            clinician_bsnr: None,
        };
        let pdf = render_clinical_layout(&doc).unwrap();
        assert!(pdf.starts_with(b"%PDF-1.4"));
        let text = String::from_utf8_lossy(&pdf);
        assert!(text.contains("QUITTUNG") || text.contains("Receipt") || text.contains("\\321"));
    }

    #[test]
    fn unknown_kind_falls_back_to_generic() {
        let doc = ClinicalPdfLayout {
            kind: "unknown_type".into(),
            practice_lines: practice(),
            header_right_lines: vec![],
            meta_lines: vec![],
            address_lines: vec![],
            document_title: "Other Document".into(),
            document_subtitle: None,
            intro_paragraphs: vec!["Inhalt".into()],
            label_value_rows: vec![],
            two_column: None,
            tables: vec![],
            detail_records: vec![],
            totals: vec![],
            closing_paragraphs: vec![],
            signature_lines: vec![],
            footer_meta_lines: vec![],
            clinician_professional_title: None,
            clinician_zanr: None,
            clinician_bsnr: None,
        };
        let pdf = render_clinical_layout(&doc).unwrap();
        assert!(pdf.starts_with(b"%PDF-1.4"));
    }

    #[test]
    fn table_with_long_cells_wraps_within_columns() {
        let doc = ClinicalPdfLayout {
            kind: "certificate".into(),
            practice_lines: practice(),
            header_right_lines: vec![],
            meta_lines: vec![],
            address_lines: vec![],
            document_title: "Test".into(),
            document_subtitle: None,
            intro_paragraphs: vec![],
            label_value_rows: vec![],
            two_column: None,
            tables: vec![PdfTableSpec {
                title: Some("Findings".into()),
                headers: vec!["Zahn".into(), "Befund".into(), "Notiz".into()],
                rows: vec![vec![
                    "21".into(),
                    "Erhebliche Karies an der mesialen Approximalfläche \
                     mit vermutlich pulpennaher Tiefe"
                        .into(),
                    "Röntgen empfohlen".into(),
                ]],
                column_layout: TableColumnLayout::Even,
            }],
            detail_records: vec![],
            totals: vec![],
            closing_paragraphs: vec![],
            signature_lines: vec![],
            footer_meta_lines: vec![],
            clinician_professional_title: None,
            clinician_zanr: None,
            clinician_bsnr: None,
        };
        let pdf = render_clinical_layout(&doc).unwrap();
        assert!(pdf.starts_with(b"%PDF-1.4"));
    }

    #[test]
    fn detail_records_box_sizes_to_content() {
        let doc = ClinicalPdfLayout {
            kind: "certificate".into(),
            practice_lines: practice(),
            header_right_lines: vec![],
            meta_lines: vec![],
            address_lines: vec![],
            document_title: "Test".into(),
            document_subtitle: None,
            intro_paragraphs: vec![],
            label_value_rows: vec![],
            two_column: None,
            tables: vec![],
            detail_records: vec![DetailRecord {
                kind: "SICK_LEAVE".into(),
                period: "19.04.2026 – 23.04.2026".into(),
                details: vec![
                    "Postoperative Wundheilung nach Weisheitszahn-Operation 38".into(),
                    "Körperliche Schonung empfohlen".into(),
                ],
            }],
            totals: vec![],
            closing_paragraphs: vec![],
            signature_lines: vec![],
            footer_meta_lines: vec![],
            clinician_professional_title: None,
            clinician_zanr: None,
            clinician_bsnr: None,
        };
        let pdf = render_clinical_layout(&doc).unwrap();
        assert!(pdf.starts_with(b"%PDF-1.4"));
    }

    #[test]
    fn multi_page_receipt_renders() {
        // Generate many intro_paragraphs to force a page break
        let mut intros = Vec::new();
        for i in 0..40 {
            intros.push(format!(
                "Absatz Nummer {i}: lorem ipsum dolor sit amet, consectetur \
                 adipiscing elit. Sed do eiusmod tempor incididunt ut labore et \
                 dolore magna aliqua."
            ));
        }
        let doc = ClinicalPdfLayout {
            kind: "receipt".into(),
            practice_lines: practice(),
            header_right_lines: vec![],
            meta_lines: meta(),
            address_lines: vec!["Empfänger".into()],
            document_title: "QUITTUNG".into(),
            document_subtitle: None,
            intro_paragraphs: intros,
            label_value_rows: vec![],
            two_column: None,
            tables: vec![],
            detail_records: vec![],
            totals: vec![LabelValue {
                label: "Total".into(),
                value: "100,00 €".into(),
            }],
            closing_paragraphs: vec![],
            signature_lines: vec![],
            footer_meta_lines: vec![],
            clinician_professional_title: None,
            clinician_zanr: None,
            clinician_bsnr: None,
        };
        let pdf = render_clinical_layout(&doc).unwrap();
        let text = String::from_utf8_lossy(&pdf);
        // Sollte mehrere /Page-Objekte enthalten
        let page_objs = text.matches("/Type /Page ").count();
        assert!(
            page_objs >= 2,
            "expected multi-page PDF, got {} pages",
            page_objs
        );
    }

    #[test]
    fn plain_preview_uses_clinical_library_letterhead_and_footer() {
        let pdf = render_plain_preview(
            "certificate",
            "Standardvorlage",
            "Mit freundlichen Grüßen",
            11,
            &[
                "Zahnarztpraxis Nord".into(),
                "Patient: Max Mustermann".into(),
                "Diagnosis: K02.1".into(),
            ],
        )
        .unwrap();
        let text = String::from_utf8_lossy(&pdf);
        assert!(pdf.starts_with(b"%PDF-1.4"));
        assert!(text.contains("Standardvorlage"));
        assert!(text.contains("Seite 1 from 1") || text.contains("(Seite"));
        assert!(text.contains("630f") || text.contains("DSGVO"));
    }
}
